-- Circuitos: dibujo propio y partes tomadas de Caminos.
-- Aplicar como una sola migración en el proyecto TrackApp. No mueve las Rutas viejas.
begin;

create table public.circuitos (
  id bigint generated by default as identity primary key,
  perfil_id uuid not null references public.perfiles(id),
  nombre varchar(120) not null check (length(trim(nombre)) > 0),
  actividad public.actividad_ruta not null,
  puntos jsonb not null check (jsonb_typeof(puntos) = 'array' and jsonb_array_length(puntos) >= 2),
  partes jsonb not null check (jsonb_typeof(partes) = 'array' and jsonb_array_length(partes) >= 1),
  caminos_base jsonb not null default '[]'::jsonb check (jsonb_typeof(caminos_base) = 'array'),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  eliminado_en timestamptz
);

create index circuitos_vivos_por_id on public.circuitos (id) where eliminado_en is null;
create index circuitos_por_autor on public.circuitos (perfil_id, id);

create trigger t_circuitos before update on public.circuitos
  for each row execute function public.marcar_actualizado_en();

create function privado.cuidar_circuito_al_cambiar()
returns trigger language plpgsql set search_path = '' as $$
begin
  if old.eliminado_en is not null then
    raise exception 'Un Circuito retirado no se puede recuperar ni modificar.';
  end if;
  if new.perfil_id is distinct from old.perfil_id or new.creado_en is distinct from old.creado_en then
    raise exception 'No se puede cambiar quién creó el Circuito ni cuándo se creó.';
  end if;
  return new;
end;
$$;
revoke all on function privado.cuidar_circuito_al_cambiar() from public;
create trigger circuitos_cuidar_al_cambiar before update on public.circuitos
  for each row execute function privado.cuidar_circuito_al_cambiar();

alter table public.circuitos enable row level security;
create policy circuitos_ver on public.circuitos for select to authenticated using (true);
create policy circuitos_crear on public.circuitos for insert to authenticated
  with check (perfil_id = (select auth.uid()) and eliminado_en is null
    and (select privado.categoria_de_quien_usa()) in ('administrador', 'premium'));
create policy circuitos_editar_propios on public.circuitos for update to authenticated
  using (perfil_id = (select auth.uid()) and eliminado_en is null
    and (select privado.categoria_de_quien_usa()) = 'premium')
  with check (perfil_id = (select auth.uid()));
create policy circuitos_editar_todos_el_administrador on public.circuitos for update to authenticated
  using (eliminado_en is null and (select privado.categoria_de_quien_usa()) = 'administrador')
  with check ((select privado.categoria_de_quien_usa()) = 'administrador');

revoke all on table public.circuitos from public, anon, authenticated;
revoke delete, truncate on table public.circuitos from service_role;
grant select on table public.circuitos to authenticated;
grant insert (perfil_id, nombre, actividad, puntos, partes, caminos_base)
  on table public.circuitos to authenticated;
grant update (nombre, actividad, puntos, partes, caminos_base, eliminado_en)
  on table public.circuitos to authenticated;

-- Cada corrección del dibujo de un Camino conserva la pareja anterior/nueva.
-- Circuitos puede trasladar sus partes una versión por vez, incluso si se
-- corrigió varias veces antes de que alguien lo vuelva a abrir.
create table public.correcciones_de_caminos (
  id bigint generated by default as identity primary key,
  camino_id bigint not null references public.caminos(id),
  version_anterior integer not null,
  version_nueva integer not null,
  geometria_anterior jsonb not null,
  geometria_nueva jsonb not null,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  eliminado_en timestamptz,
  constraint correcciones_version_siguiente check (version_nueva = version_anterior + 1),
  constraint correcciones_unicas unique (camino_id, version_anterior)
);
create trigger t_correcciones_de_caminos before update on public.correcciones_de_caminos
  for each row execute function public.marcar_actualizado_en();
alter table public.correcciones_de_caminos enable row level security;
create policy correcciones_de_caminos_ver on public.correcciones_de_caminos
  for select to authenticated using (true);
revoke all on table public.correcciones_de_caminos from public, anon, authenticated;
revoke delete, truncate on table public.correcciones_de_caminos from service_role;
grant select on table public.correcciones_de_caminos to authenticated;

create function privado.recordar_correccion_de_camino()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.geometria is distinct from old.geometria then
    insert into public.correcciones_de_caminos
      (camino_id, version_anterior, version_nueva, geometria_anterior, geometria_nueva)
    values (old.id, old.version_forma, new.version_forma, old.geometria, new.geometria);
  end if;
  return new;
end;
$$;
revoke all on function privado.recordar_correccion_de_camino() from public;
create trigger caminos_recordar_correccion after update of geometria on public.caminos
  for each row execute function privado.recordar_correccion_de_camino();

commit;
